### ISSUE TITLE
진조가 확인해야 하는 사항

### ISSUE THREAD

**Issue by sunseo18** [Sungshin-PoHab/PoHab_Front#31]
1. Guideline3에서 부서 누르면 지원하기 하는 과정(나의 saveStatus함수)이 빠져서 지원이 안되길래 다시 수정했어유

그리고 제 함수말고 goApplyQuestion()이라는 리다이렉트만 하는 함수로 바뀌었는데 이 친구는 /apply/partyId/stepId으로 리다이렉트하는데 원래 /apply/departmentId/stepId로 하는게 맞아서(Routers에도 그렇게 돼있음!) 이거도 수정했거든요??

이렇게 두 개 수정함으로써 생기는 문제가 없는지 궁금합니다!

**Comment by zinzo1019** [comment]
완전 짱인 거 같습니다
