### ISSUE TITLE
[단계 & 부서 등록 플로우] 단계 등록 -> 부서 등록으로 이동하는 버튼 클릭 시 url 이상해짐

### ISSUE THREAD

**Issue by zinzo1019** [Sungshin-PoHab/PoHab_Front#35]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/79037318/185760276-8e4cdffe-daea-4e30-b8df-2b4c89598117.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/79037318/185760306-3057c677-ca5b-4a51-8bae-453d70fba597.png">

**Comment by sunseo18** [comment]
제가 수정했슴다
